# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: altoro_j
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501

from typing import Any
from httpx import Response

from restcodegen.restclient import Client


from clients.http.altoro_j.models.api_models import (
    Dates,
)


class Field2AccountApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_account(
        self,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.get_account_with_http_info(
            authorization=authorization,
            **kwargs,
        )
        return response

    def get_account_with_http_info(
        self,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "Authorization": str(authorization),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}

        headers.update(kwargs.pop("headers", {}))

        response = self.api_client.get(
            url="/account",
            headers=headers,
            **kwargs,
        )
        return response

    def get_account_account_no(
        self,
        account_no: Any,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    account_no(Any, required): Account id
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.get_account_account_no_with_http_info(
            account_no=account_no,
            authorization=authorization,
            **kwargs,
        )
        return response

    def get_account_account_no_with_http_info(
        self,
        account_no: Any,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    account_no(Any, required): Account id
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "Authorization": str(authorization),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}

        headers.update(kwargs.pop("headers", {}))

        response = self.api_client.get(
            url=f"/account/{account_no}",
            headers=headers,
            **kwargs,
        )
        return response

    def get_account_account_no_transactions(
        self,
        account_no: Any,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    account_no(Any, required): Account id
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.get_account_account_no_transactions_with_http_info(
            account_no=account_no,
            authorization=authorization,
            **kwargs,
        )
        return response

    def get_account_account_no_transactions_with_http_info(
        self,
        account_no: Any,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    account_no(Any, required): Account id
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "Authorization": str(authorization),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}

        headers.update(kwargs.pop("headers", {}))

        response = self.api_client.get(
            url=f"/account/{account_no}/transactions",
            headers=headers,
            **kwargs,
        )
        return response

    def post_account_account_no_transactions(
        self,
        dates: Dates,  # noqa: E501
        account_no: Any,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    dates(Dates): ...
                    account_no(Any, required): Account id
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.post_account_account_no_transactions_with_http_info(
            account_no=account_no,
            dates=dates,  # noqa: E501
            authorization=authorization,
            **kwargs,
        )
        return response

    def post_account_account_no_transactions_with_http_info(
        self,
        dates: Dates,  # noqa: E501
        account_no: Any,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    dates(Dates): ...
                    account_no(Any, required): Account id
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "Authorization": str(authorization),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}

        headers.update(kwargs.pop("headers", {}))

        content = dates.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.post(
            url=f"/account/{account_no}/transactions",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response
