# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: altoro_j
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501

from typing import Any
from httpx import Response

from restcodegen.restclient import Client


from clients.http.altoro_j.models.api_models import (
    Transfer,
)


class Field3TransferApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def post_transfer(
        self,
        transfer: Transfer,  # noqa: E501
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    transfer(Transfer): ...
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.post_transfer_with_http_info(
            transfer=transfer,  # noqa: E501
            authorization=authorization,
            **kwargs,
        )
        return response

    def post_transfer_with_http_info(
        self,
        transfer: Transfer,  # noqa: E501
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    transfer(Transfer): ...
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "Authorization": str(authorization),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}

        headers.update(kwargs.pop("headers", {}))

        content = transfer.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.post(
            url="/transfer",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response
