# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: altoro_j
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501

from typing import Any
from httpx import Response

from restcodegen.restclient import Client


from clients.http.altoro_j.models.api_models import (
    Feedback,
)


class Field4FeedbackApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def post_feedback_submit(
        self,
        feedback: Feedback,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            feedback(Feedback): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response = self.post_feedback_submit_with_http_info(
            feedback=feedback,  # noqa: E501
            **kwargs,
        )
        return response

    def post_feedback_submit_with_http_info(
        self,
        feedback: Feedback,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            feedback(Feedback): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = feedback.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.post(
            url="/feedback/submit",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def get_feedback_feedback_id(
        self,
        feedback_id: Any,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    feedback_id(Any, required): ...
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.get_feedback_feedback_id_with_http_info(
            feedback_id=feedback_id,
            authorization=authorization,
            **kwargs,
        )
        return response

    def get_feedback_feedback_id_with_http_info(
        self,
        feedback_id: Any,
        authorization: Any,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    feedback_id(Any, required): ...
                    authorization(Any, required): Authorization token (provided upon successful
        login)
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "Authorization": str(authorization),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}

        headers.update(kwargs.pop("headers", {}))

        response = self.api_client.get(
            url=f"/feedback/{feedback_id}",
            headers=headers,
            **kwargs,
        )
        return response
