# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: altoro_j
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501

from typing import Any
from httpx import Response

from restcodegen.restclient import Client


class Field6LogoutApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_logout(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response = self.get_logout_with_http_info(
            **kwargs,
        )
        return response

    def get_logout_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url="/logout",
            headers=headers,
            **kwargs,
        )
        return response
