"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: altoro_j
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501
from clients.http.altoro_j.apis.3_transfer_api import Field3TransferApi
from clients.http.altoro_j.apis.4_feedback_api import Field4FeedbackApi
from clients.http.altoro_j.apis.5_admin_api import Field5AdminApi
from clients.http.altoro_j.apis.1_login_api import Field1LoginApi
from clients.http.altoro_j.apis.6_logout_api import Field6LogoutApi
from clients.http.altoro_j.apis.2_account_api import Field2AccountApi

__all__ = [
    "Field3TransferApi",
    "Field4FeedbackApi",
    "Field5AdminApi",
    "Field1LoginApi",
    "Field6LogoutApi",
    "Field2AccountApi",
]