"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: petstore
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501

from clients.http.petstore.apis.user_api import UserApi
from clients.http.petstore.apis.store_api import StoreApi
from clients.http.petstore.apis.pet_api import PetApi

__all__ = [
    "UserApi",
    "StoreApi",
    "PetApi",
]
